// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA16rlHsURT_CeAZj-N2b8fe8QIue3iET0',
    appId: '1:122088837656:android:08c020f0aac4ca47fc296d',
    messagingSenderId: '122088837656',
    projectId: 'lion-2d2db',
    storageBucket: 'lion-2d2db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqx9bHJTNMqhZz1L-Zf1jjXlrHhHXN3Jg',
    appId: '1:122088837656:ios:9a454d24ae08723efc296d',
    messagingSenderId: '122088837656',
    projectId: 'lion-2d2db',
    storageBucket: 'lion-2d2db.firebasestorage.app',
    iosBundleId: 'com.example.liOn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqx9bHJTNMqhZz1L-Zf1jjXlrHhHXN3Jg',
    appId: '1:122088837656:ios:9a454d24ae08723efc296d',
    messagingSenderId: '122088837656',
    projectId: 'lion-2d2db',
    storageBucket: 'lion-2d2db.firebasestorage.app',
    iosBundleId: 'com.example.liOn',
  );
}
